server:
  port: 8086
spring:
  profiles:
    active: dev
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        enabled: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml