server:
  port: 8089
spring:
  profiles:
    active: dev
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        enabled: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml

mq-consumer:
  follow-unfollow:
    rate-limit: 1200 # 每秒处理多少条